
training_data: projects/pc530-fao-fra-rss/assets/reference/split/training_sample
testing_data: projects/pc530-fao-fra-rss/assets/reference/split/testing_sample
image: 
  type: composite
  features: ['B1','B2','B3','B4','B5']
  start_date: 2017-01-01
  end_date: 2019-12-31
  cloud_mask: True
classifier:
  name: randomforest
  dest: projects/pc530-fao-fra-rss/assets/models/randomforest-v3
  pre_compute_training: projects/pc530-fao-fra-rss/assets/reference/split/training_sample_s2
  init_args:
    numberOfTrees: 100
    seed: 42
    maxNodes: 2
    minLeafPopulation: 1000
    bagFraction: 0.67
  train_args:
    classProperty: label