experiment_name: resnet-jjd-bce-sum-gap
model_name: resnet
data_dir: tfrecords/balanced
checkpoint: saved_models/TESTresnet-jjd-bce-sum-gap/best_model.h5
total_examples: 77046 # number of geotiffs not tfrecords
data_split: 0.2

optimizer: adam
optimizer_use_lr_schedular: true
loss_function: bce_sum

epochs: 15
learning_rate: 0.01
batch_size: 100
buffer_size: 77046

early_stopping_patience: 5 # null or int
