experiment_name: "mobilenet_v3small_kdw_v4_test_valsplit"
model_name: "mobilenet_v3small"
data_dir: "tfrecords/balanced"
total_examples: 1000 # number of geotiffs not tfrecords
test_split: 0.2
val_split: 0.1

optimizer: "adam"
optimizer_use_lr_schedular: true
loss_function: "binary_crossentropy"

epochs: 2
learning_rate: 0.01
batch_size: 64
buffer_size: 1000

early_stopping_patience: 5 # null or int