experiment_name: "mobilenet_v3small_kdw_v1"
model_name: "mobilenet_v3small"
data_dir: "tfrecords/balanced"
total_examples: 77046 # number of geotiffs not tfrecords
data_split: 0.2

optimizer: "adam"
optimizer_use_lr_schedular: true
loss_function: "binary_crossentropy"

epochs: 15
learning_rate: 0.01
batch_size: 255
buffer_size: 77046

early_stopping_patience: 5 # null or int
