model_name: "resnet"
data_dir: "C:\\fao-models\\tfrecords"
total_examples: 18149 # number of geotiffs not tfrecords
data_split: 0.2
epochs: 1000
learning_rate: 0.01
batch_size: 32
buffer_size: 1000
optimizer: "adam"
loss_function: "binary_crossentropy"
early_stopping_patience: 7
