experiment_name: "mobilenet_v3small_try1"
model_name: "mobilenet_v3small"
data_dir: "data_balanced"
total_examples: 77046 # number of geotiffs not tfrecords
data_split: 0.2

optimizer: "adam"
optimizer_use_lr_schedular: true
loss_function: "binary_crossentropy"

epochs: 50
learning_rate: 0.001
batch_size: 512
buffer_size: 77046

early_stopping_patience: null # null or int
