experiment_name: "del-test-lr"
model_name: "resnet"
data_dir: "tfrecords/balanced"
total_examples: 77046 # number of geotiffs not tfrecords
data_split: 0.2

optimizer: "adam"
optimizer_use_lr_schedular: true
loss_function: "binary_crossentropy"

epochs: 50
learning_rate: 0.01
batch_size: 512
buffer_size: 77046

early_stopping_patience: null # null or int
