experiment_name: "vgg16_try1"
model_name: "vgg16"
data_dir: "data_balanced"
total_examples: 77046 # number of geotiffs not tfrecords
data_split: 0.2

optimizer: "adam"
optimizer_use_lr_schedular: true
loss_function: "binary_crossentropy"

epochs: 100
learning_rate: 0.01
batch_size: 128
buffer_size: 77046

early_stopping_patience: null # null or int
